### ISSUE TITLE
Infinite chat doesn't load old chat when it is been a long time

### ISSUE THREAD

**Issue by timbl** [SolidOS/solid-ui#522]
When the archives has accidentally not been updated since November, then going to a long chat would load the message composition widget but no previous data in the chat. Looks like the function of skipping back to the last data present doesn't work.

**Comment by bourgeoa** [comment]
The issue seems coming from the promise erroring on caching a previous 404
 
1.  a new month : 
```
fetcher.js:1131 Uncaught (in promise) Error: Fetcher: <https://solidos.solidcommunity.net/Team/SolidOs%20team%20chat/2022/12/> Not Found
    at e.value (fetcher.js:1131:17)
    at fetcher.js:1858:26
```

2. create a message
3. error
```
Uncaught (in promise) Error: Fetcher: Previously failed: 404
    at e.value (fetcher.js:1131:17)
    at e.value (fetcher.js:946:23)
    at e.value (fetcher.js:815:83)
    at e.value (fetcher.js:803:19)
    at dateFolder.js:138:62
    at f (regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (regeneratorRuntime.js:125:22)
    at Generator.next (regeneratorRuntime.js:69:21)
    at t (asyncToGenerator.js:3:20)
    at s (asyncToGenerator.js:22:9)
```
4. logout and login : old messages are correctly displayed
